name: Actualisation des donnees des deputes

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  recuperer-les-donnees:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupérer le dossier
        uses: actions/checkout@v4

      - name: 2. Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Installer les dépendances
        run: pip install -r requirements.txt

      - name: 4. Lancer le script d'extraction
        run: python scraper.py

      - name: 5. Sauvegarder le CSV généré
        run: |
   
          git config --global user.name 'Robot GitHub'
          git config --global user.email 'action@github.com'
          
          # On dit à Git d'ajouter TOUS les nouveaux fichiers générés par le script
          git add deputes_normands_complet.json deputes_normands_resume.csv
          
          # On enregistre et on pousse sur le dépôt uniquement s'il y a du changement
          git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour des données Civix"
          git push  
