name: Actualisation des donnees des deputes

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  recuperer-les-donnees:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupérer le dossier
        uses: actions/checkout@v4

      - name: 2. Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Installer les dépendances
        run: pip install -r requirements.txt

      - name: 4. Lancer le script d'extraction
        run: python scraper.py

      - name: 5. Sauvegarder le CSV généré
        run: |
          git config --global user.name 'Robot GitHub'
          git config --global user.email 'action@github.com'
          
          # On vérifie si le fichier existe vraiment avant de l'ajouter
          if [ -f deputes_normands.csv ]; then
            echo "Le fichier CSV existe. Sauvegarde en cours..."
            git add deputes_normands.csv
            git diff --quiet && git diff --staged --quiet || git commit -m "Mise à jour quotidienne des données"
            git push
          else
            echo "ERREUR CRUCIALE : Le script Python (Etape 4) n'a pas généré le fichier 'deputes_normands.csv'."
            echo "Veuillez consulter les lignes de texte de l'Étape 4 pour comprendre pourquoi l'API a échoué."
            exit 1
          fi
